codecov:
  require_ci_to_pass: yes
   fixes:
  - "io/github/config4k::src/main/io.github.config4k"

coverage:
  precision: 2
  round: down
  range: "5...100"
 

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no