CREATE TABLE SELIC(
    ID UNIQUEIDENTIFIER PRIMARY KEY,
    TITLE VARCHAR(10) NOT NULL,
    REFERENCE_DATE DATETIME,
    SELIC_CODE BIGINT,
    EMISSION DATETIME,
    DUE_DATE DATETIME,
    PURCHASE_TAX DECIMAL,
    SELL_TAX DECIMAL,
    INDICATIVE_TAX DECIMAL,
    PU BIGINT,
    STANDARD_DEVIATION DECIMAL,
    INTERVAL_MIN_DAY_ZERO DECIMAL,
    INTERVAL_MAX_DAY_ZERO DECIMAL,
    INTERVAL_MIN_DAY_ONE DECIMAL,
    INTERVAL_MAX_DAY_ONE DECIMAL,
    STATUS VARCHAR(24)
);