name: CI-CD
on:
  push:
    branches:
    - master
    - feature/*
    - hotfix/*
jobs:
  dotnet-step:
    name: build and test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: restore
      run: dotnet restore
    - name: build
      run: dotnet build --configuration Debug --no-restore
    - name: test
      run: dotnet test --no-build --no-restore --verbosity normal
      
  docker-step:
    name: build docker image and publish
    needs: dotnet-step
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: create docker image
      run: docker build . --file Dockerfile --tag anbima-consumer-api:$(date +%s)
