name: CI-CD
on:
  push:
    branches:
    - master
    - feature/*
    - hotfix/*
jobs:
  dotnet-step:
    name: dotnet test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: restore
      run: dotnet restore
    - name: build
      run: dotnet build --configuration Debug --no-restore
    - name: test
      run: dotnet test --no-build --no-restore --verbosity normal
      
  docker-step:
    name: docker publish
    env:
      image_name: anbima_consumer_api
      image_id: docker.pkg.github.com/${{ github.repository }}/$image_name
    needs: dotnet-step
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $image_name

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
      - name: to lowercase
        run: $image_id=$(echo $image_id | tr '[A-Z]' '[a-z]')
         
      - name: tag
        run: docker tag image $image_id:latest
      - name: push
        run:  docker push $image_id:latest
