name: dotnet Testing
on:
  push:
    branches: 
      - master
      - feature/*
jobs:
  test:
    name: setup .net core 3.1 on windows 2019
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: restoring dependencies
      run: dotnet restore
      
    - name: building
      run: dotnet build --configuration Debug --no-restore
      
    - name: Testing
      run: dotnet test --no-build --no-restore
