name: dotnet-retoring-nuget
on:
  push:
    branches:
    - master
    - feature/*
    - hotfix/*
jobs:
  Setup:
    name: Setup .net core 3.1
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
  
  dotnet-restore:
    runs-on: ubuntu-18.04
    needs: Setup
    steps: 
      - name: Restoring
        run: dotnet restore
      
  dotnet-build:
    name: building
    runs-on: ubuntu-18.04
    needs: dotnet-restore
    steps:
      - name: Build
        run: dotnet build --configuration Debug --no-restore
      
  dotnet-test:
    name: testing
    runs-on: ubuntu-18.04
    needs: dotnet-build
    steps:
      - name: Test
        run: dotnet test --no-build --no-restore --verbosity normal
