name: dotnet Testing
on:
  push:
    branches:
    - master
    - feature/*
    - hotfix/*
jobs:
  Setup:
    name: Build and Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Develop --no-restore
    - name: Test
      run: dotnet test --no-restore --no-build
